### ISSUE TITLE
프로젝트 환경 구축 

### ISSUE THREAD

**Issue by sudago** [jazz-meet/jazz-meet#10]
## Tasks
- [x] entity 설계
- [x] 예외처리 관련 코드
    - [x] 에러 공통 응답 형식
- [x] cors
- [x] querydsl 의존성 설정

## 기타

<-- 기타 사항을 적어주세요 -->
