### ISSUE TITLE
배포 환경 및 CI/CD 파이프라인 구축

### ISSUE THREAD

**Issue by chunghye98** [jazz-meet/jazz-meet#11]
## Tasks
- [x] EC2 생성 및 설정
- [x] RDS 생성 및 설정
- [x] github actions, docker 사용해서 cicd 파이프라인 구축
- [x] https 적용 

## 기타

<-- 기타 사항을 적어주세요 -->
