### ISSUE TITLE
이미지 업로드 및 삭제

### ISSUE THREAD

**Issue by jsjseop** [jazz-meet/jazz-meet#110]
## Feature 
- S3에 이미지를 업로드하고 URL을 반환한다.
- 이미지를 삭제 상태로 변경한다.

## Tasks
- [x] 이미지 업로드 API 구현
- [x] 이미지 삭제 API 구현
- [x] 테스트 코드 작성
