### ISSUE TITLE
특정한 공연장 검색

### ISSUE THREAD

**Issue by hjsong333** [jazz-meet/jazz-meet#116]
## Feature 
근처 공연장 또는 검색어 제안에서 공연장을 클릭할 경우의 동작.
해당 공연장만 지도와 목록에 있는 페이지로 이동하고, 공연장의 상세정보 layer를 띄운다.

## Tasks
- [x] 공연장 단독 검색 API
- [x] 지도 페이지(목록) 이동 동작
- [x] 공연장 상세 정보 열기
