### ISSUE TITLE
마커(핀) 렌더링 방식 변경

### ISSUE THREAD

**Issue by jsh3418** [jazz-meet/jazz-meet#124]
## 이슈
지도에 마커(핀)를 클릭하면 마커(핀)가 재렌더링 되는 이슈

![Nov-07-2023 17-49-15](https://github.com/jazz-meet/jazz-meet/assets/57666791/c350be66-6efd-4b95-8a50-6a974eb88550)

## 문제 분석(현재 동작 방식)

지도에 마커(핀)를 클릭 → navigate 공연장 상세보기 → 마커(핀) 업데이트(useEffect에 useLocation가 걸려있다.)

그래서 지도페이지에서 주소가 변하면 계속해서 마커(핀)은 재렌더링될 것이다. 추후 업데이트에 사이드 이펙트가 될 것으로 예상된다.

## 해결 방법

마커(핀) 업데이트를 useLocation이 바뀔 때마다 업데이트를 하는 것이 아닌 직접 호출하여 컨트롤 하도록 수정해야한다.

## Tasks
- [x] 마커(핀) 렌더링 방식 변경
  - [x] 마커(핀) 좌표 가져오기 분리
  - [x] 공연장 목록 가져오기 분리
  - [x] 마커(핀)과 공연장 목록 렌더링을 마커(핀), 공연장 목록을 기준(useEffect의 종속성 배열에 넣기)으로 렌더링 되도록 수정하기

**Comment by hjsong333** [comment]
URL을 기준으로 path, querystring에 따라 지도 페이지의 동작이 구분되므로,
URL을 분석해서 다루기 쉬운 상태로 반환해주는 hook 추가하는게 좋아보임.

폐기 
1. path로 분기 처리할 로직이 없음
2. 상황별로 처리하는 함수를 만들어서 직접 호출

**Comment by hjsong333** [comment]
### map, list를 렌더링하기 위해 필요한 것
- 데이터 조회
- 렌더링

### 쿼리에 따라 데이터를 조회 => `hook`
- pins
- venues 

### 데이터 상태를 컴포넌트로 전달하여 렌더링 => `props`

- Map 컴포넌트로 2개 상태를 넘겨 지도를 그린다.
- Panel 컴포넌트로 venues를 넘겨 목록을 그린다.
