### ISSUE TITLE
검색 기능 오류 수정

### ISSUE THREAD

**Issue by jsh3418** [jazz-meet/jazz-meet#142]
## Feature 
핀 업데이트 방식 변경 이후 검색 기능이 되지 않아 이 부분 수정

## Tasks
- [x] 첫 렌더링 시 검색으로 들어온 것인지 구분하여 마커(핀), 목록 조회 API 분기처리
- [x] 기존의 '현 지도에서 검색' 버튼 클릭시 좌표를 추가하여 navigate 로직 삭제
- [x] pins가 다 보이도록 fitBounds 호출
