### ISSUE TITLE
공연 일정 조회, 렌더링 구현

### ISSUE THREAD

**Issue by hjsong333** [jazz-meet/jazz-meet#162]
## Feature 
공연 페이지에서 선택한 월, 일의 공연 정보를 렌더링하는 기능입니다.
지역 아래 공연장, 공연장 별로 공연을 리스트 업 해서 보여줍니다.
공연장을 클릭하면 공연장 상세 페이지로 이동합니다.

## Tasks
- [x] 공연 일정이 있는 날짜 조회 API 호출 함수
- [x] 선택된 날짜 공연 조회 API 호출 함수
- [x] 공연이 없는 날짜 비활성화
- [x] 월 변경 시, 공연이 없는 날짜면 이후/이전의 가장 가까운 날로 변경
- [x] 선택된 날짜의 공연 조회
- [x] 공연장 클릭 시 공연장 상세페이지로 이동
## 기타
화면 너비 별로 공연장 카드 너비 조정

**Comment by hjsong333** [comment]
목표
- 공연 있는 날만 선택된다.
- 초기화, 월 이동 시에도 이 규칙은 적용된다.

상황
- selectedDate는 오늘 Date 객체다.
- 공연이 있는 날을 조회하기 위해서는 Date 객체가 필요하다.
- selectedDate가 변경되면, 해당 달의 일자 객체들을 재생성한다.(불필요)

**Comment by hjsong333** [comment]
```TypeScript
  useEffect(() => {
    const updateShowDates = async () => {
      const showDates = await getShowDates();

      setShowDates(showDates);
    };

    setDatesInMonth(getMonthDates(selectedDate));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [selectedMonth]);

  useEffect(() => {
    setCenterDateIndex(selectedDate.getDate() - 1);
  }, [selectedDate]);
```
### 문제 상황
월 변경 시에만 datesInMonth를 업데이트하기 위해서 useEffect를 분리하려고 했다.
공연이 있는 날을 알기 위해서 공연이 있는지 없는지 불확실한 날을 select 해야한다.

select 한 날이 변경되면 해당 일자의 공연 정보를 불러오도록 구현하려고 하기 때문에, 만약 공연이 없는 날이라면 공연 조회 API를 2번 호출하게 된다.

**Comment by hjsong333** [comment]
가장 가까운 날짜 뽑는 함수
```TypeScript
const getClosestShowDate = (dates: number[], date: Date) => {
  const dateNumber = date.getDate();
  const showDates = [...dates].sort((prev, next) => prev - next);

  if (showDates.includes(dateNumber)) {
    return date;
  }

  if (showDates.length === 0) {
    throw new Error('No show date found');
  }

  const showDateIndex = showDates.findIndex((showDate) => showDate > dateNumber);

  if (showDateIndex === -1) {
    return new Date(date.getFullYear(), date.getMonth(), showDates[showDates.length - 1]);
  }

  return new Date(date.getFullYear(), date.getMonth(), showDates[showDateIndex]);
};
```
