### ISSUE TITLE
지도 관련 오류 및 개선

### ISSUE THREAD

**Issue by jsh3418** [jazz-meet/jazz-meet#184]
## Feature 
지도 관련 오류 수정

## Tasks
- [x] 검색 기능 오류 수정
  - [x] 추천검색어에서 공연장 상세보기 오류 수정
- [x] 현 지도에서 검색 버튼 클릭시 지도 이동 현상 수정
  - [x] pins 업데이트와 fitBounds 함수 분리
- [x] 헤더의 지도 버튼을 클릭하면 모든 상태(지도, 검색 등)가 초기화 된다.
- [x] 공연장 클릭 시(특정 공연장의 상세보기가 활성화) 마커 UI 변경
  - [x] 선택한 공연장으로 지도 이동
- [x] 핀을 호버했을 때
  - [x] 마커로 보이도록 수정
  - [x] 맨 앞으로(z-index) 보이도록 수정
- [x] 검새 시 `현 지도에서 검색 버튼`이 자동으로 나타나는 현상 수정
- [x] 공연장 상세 페이지 열면, 마커(핀) 목록이 현재 지도 기준으로 다시 조회되는 현상 수정
- [x] 공연장 상세페이지가 열릴 때 마커 선택이 안 되는 문제 수정
  - [x] 상세 페이지를 닫을 때 마커 초기화가 안 되는 문제 수정
  - [x] 공연장 목록으로 상세페이지를 열 때 마커를 지도 중심으로 이동
- [x] 마커위치 미세조정
- [x] 상세 페이지가 열린 상태에서 현 지도 검색 후 목록에 공연장이 없으면, 목록으로 돌아간다.
  - 검색 결과에 공연장이 있다면? 그래도 목록으로 가나?
- [x] 상세 페이지가 열린 상태에서 새로고침하면 마커가 없어짐

**Comment by hjsong333** [comment]
검색 후 마커 선택을 빠른 속도로 할 때, 
마커를 중심으로 이동하는 기능이 잘 잘동되지 않는 현상이 있음.

- 검색 했을 때 enableFitBounds를 true로 변경한 후, fitBoundsToCoordinates()이 실행된다.
- 이후 enableFitBounds를 초기화 하지 않아서 fitBoundsToCoordinates가 계속해서 실행되기 때문에 발생한 문제.

**Comment by hjsong333** [comment]
검새 시 현 지도에서 검색 버튼이 자동으로 나타나는 현상 수정

- zoom_changed 이벤트를 대체할 UI 이벤트가 naver maps에서 제공되지 않음(예: wheel event)
- zoom_changed 이벤트 리스너 제거해서 해결.

**Comment by hjsong333** [comment]
새로고침하거나 복사한 URL로 접속하더라도 동일한 마커와 목록을 유지
> URL에 현재 상태를 저장한다. 

목록, 상세, 공연 상세의 주소가 각각 분리되어 있음.
하지만, 사용자 입장에서는 같은 페이지로 인식되기 때문에 상태를 계속해서 유지해줄 필요가 있다.
때문에 경로 대신 쿼리스트링을 사용하기로 함.

대비해야하는 케이스
- 키워드 검색
- 지도 뷰 검색
- 공연장 단독 검색

**Comment by hjsong333** [comment]
공연장 단독 검색 시 상세 페이지 자동으로 열기 동작 안 됨
