### ISSUE TITLE
공연장 상세보기 미구현 사항 구현

### ISSUE THREAD

**Issue by jsh3418** [jazz-meet/jazz-meet#187]
## Feature
공연장 상세보기 미구현 사항 구현

## Tasks
- [x] 뒤로가기 버튼 구현
- [x] 영업시간 [disclosure pattern](https://www.w3.org/WAI/ARIA/apg/patterns/disclosure/) 적용 + 오늘 영업시간 노출
- [x] 공연장 정보 줄바꿈 되도록 수정
- [x] 이미지 기능
  - [x] 이미지 클릭 시 상세보기
  - [x] 5장 이상 이미지 오류 수정
  - [x] 5장 미만의 공연장은 부족한 이미지 만큼 기본 이미지로 대체
  - [x] 클릭한 이미지 상세보기 열기(첫 이미지부터 보이는 것이 아님)
  - [x] 더보기 시 6번째 이미지 상세보기
- [x] 판매정보, 공연장정보 삭제
- [x] 주소, 전화번호 복사 버튼, 기능 구현

**Comment by hjsong333** [comment]
### 버그
영업시간을 펼친 상태로 다른 공연장 상세보기로 넘어가면 펼쳐진 상태가 유지된다.

**Comment by hjsong333** [comment]
상세보기 여닫기 시 애니메이션이 제대로 작동하지 않음.
열릴 때 뿐만아니라 닫힐 때도 애니메이션이 있으면 좋겠다는 피드백을 받음.
