### ISSUE TITLE
검색창 기능 오류 수정

### ISSUE THREAD

**Issue by hjsong333** [jazz-meet/jazz-meet#193]
## Feature 
QA에서 피드백 받은 검색창의 오동작들을 수정한다.

## Tasks
- [x] 검색창 placeholder 변경(지역 또는 공연장 명을 입력해주세요.)
- [x] 검색 후, 검색어 삭제가 안 되는 현상 수정
- [x] 추천 검색어 중 검색어 해당하는 단어 강조 표시

## 기타
헤더에 있는 로고 변경 요청도 있다.
