### ISSUE TITLE
공연장 목록 QA 피드백 반영

### ISSUE THREAD

**Issue by hjsong333** [jazz-meet/jazz-meet#205]
## Feature 
QA 피드백 받은 사항들 수정 및 구현

## Tasks
- [x] 공연장 주소와 상세정보 사이의 간격 줄이기
- [x] 페이지 이동 시 목록 상단으로 이동
- [x] 당일 공연 없는 공연장에 **공연 없음** 표시
