### ISSUE TITLE
메인페이지 QA 피드백 반영

### ISSUE THREAD

**Issue by hjsong333** [jazz-meet/jazz-meet#208]
## Feature 
메인페이지 관련 QA 피드백 사항 반영

## Tasks
- [x] 진행중인 공연 -> 다가오는 공연으로 수정
- [x] 주변 공연장 화살표와 이미지 겹침 수정
- [x] 진행중인 공연이 없는 경우 문구 or 이미지 보여주기
- [ ] ~주변 공연장에 마우스 호버 효과~
