### ISSUE TITLE
공연 스케줄 자동화

### ISSUE THREAD

**Issue by sudago** [jazz-meet/jazz-meet#273]
## Feature 
- 인스타그램에서 공연 정보를 얻어와서 자동으로 데이터를 주입한다.

## Tasks
- [x] 인스타에서 데이터 크롤링해서 공연 스케줄이 담긴 이미지 url 추출하기
- [x] 이미지 url에서 텍스트 추출하기 (네이버 클로바 OCR 이용)
- [x] 텍스트 파싱해서 원하는 공연 데이터로 다듬기 (RequestDto)
- [x] `@Schedule` 적용해서 원하는 시간에 자동으로 공연 데이터를 넣도록 설정하기
- [x] ec2에 chrome, chrome driver 설치하기
- [ ] ec2 오류 해결하기 (봇 우회)
- [x] 이벤트가 있는 주에는 공연 일자가 늘어난다. 크롤링 로직 수정하기
- [ ] 테스트 코드 작성하기
