### ISSUE TITLE
메인 화면에서 공연 클릭 시 공연 상세페이지로 이동

### ISSUE THREAD

**Issue by hjsong333** [jazz-meet/jazz-meet#287]
## Feature
공연 상세화면 컴포넌트에 route path 할당

## Tasks
- [x] 공연 상세화면 path 설정
- [x] 공연 목록 불러오기
- [x] 공연 id로 해당 공연 찾기
