### ISSUE TITLE
리드미 꾸미기

### ISSUE THREAD

**Issue by chunghye98** [jazz-meet/jazz-meet#359]
## Tasks
- [ ] 시스템 아키텍처 추가
- [ ] CI/CD 아키텍처 추가
- [ ] 주요 기능 시각화

## 리드미 구성
1. 프로젝트 이름 및 로고
2. 소개
  - 프로젝트 목적, 동기, 해결하고자 하는 문제
3. 데모
4. 기술 스택
5. ERD 설계
6. 시스템 아키텍처
7. CICD 아키텍처
8. 주요 기능 소개
9. 트러블 슈팅
10. 회고
