### ISSUE TITLE
메인 페이지 기능 구현 (배너, 공연장, 공연)

### ISSUE THREAD

**Issue by jsh3418** [jazz-meet/jazz-meet#43]
## Feature 
메인 페이지 배너, 공연장, 공연 기능 구현

## Tasks
- [x] 배너 자동 슬라이드 구현
- [x] 공연장 기능 구현
  - [x] 주변 공연장 API 연결
  - [x] 공연장 클릭시 상세보기로 이동
- [x] 공연 기능 구현
  - [x] 진행 중인 공연 API 연결
  - [x] 진행 중인 공연 클릭시 상세보기로 이동
