### ISSUE TITLE
공연장 목록 조회 - 검색

### ISSUE THREAD

**Issue by sudago** [jazz-meet/jazz-meet#44]
## Feature 
검색어로 검색 한 공연장의 목록을 조회한다.
- 검색바에서 공연장 이름이나 공연장의 지역(위치) 이름으로 검색이 가능하다.

## Tasks
- [x] 페이징
    - 페이징이 가능하다. 현재 페이지 숫자(default = 1)와 max 페이지 숫자를 제공한다.
- [ ] 검색어
    - 검색바에서 공연장 이름이나 공연장의 지역(위치) 이름으로 검색이 가능하다.
    - [x] word가 ""(빈문자열) 이거나 null 일 때 빈 리스트를 반환하기
    - [ ] word에 띄어쓰기가 있을 때, 공백 기준으로 문자를 잘라서 contains and 로 검색하기
- [x] 테스트 코드 작성

## 기타
- `정렬 - 시간 순`과 `일자 필터`는 **공연장이 아닌 공연에 대해 적용**이 되면 좋을 것 같다는 의견이 나왔다.
- 하지만 이를 수정하려면 **공연 목록에 대한 기능**이 추가 되어야 하기 때문에 해당 기능에 대한 기획을 추후 다시 상의 하기로 했다.
- 때문에 기존 기획에서 정렬(시간순/거리순) 기능과 일자 필터 기능이 제거되었다.
