### ISSUE TITLE
진행 중인 공연 시간 포맷 수정 및 메인 페이지 style 수정

### ISSUE THREAD

**Issue by jsh3418** [jazz-meet/jazz-meet#94]
## Feature 
진행 중인 공연 시간 포맷 수정

## Tasks
- [x] 진행 중인 공연 시간 포맷 수정
- [x] footer UI 수정
- [x] 주변 공연장, 진행중인 공연 style 수정

## 기타

<img width="1226" alt="image" src="https://github.com/jazz-meet/jazz-meet/assets/57666791/97519ec0-1b99-4483-b524-09f4298b8781">

<img width="828" alt="image" src="https://github.com/jazz-meet/jazz-meet/assets/57666791/15c689f9-7981-4ba8-8637-731d9858322e">

<img width="1170" alt="image" src="https://github.com/jazz-meet/jazz-meet/assets/57666791/460abbbf-3a66-4ae4-9991-28ef0d7e8b55">
